BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes

# reviung34_rgb
RGBLIGHT_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = yes
COMBO_ENABLE = yes

# LTO_ENABLE = yes
SPACE_CADET_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

SRC += features/caps_word.c
